### ISSUE TITLE
Anpassungen gemäss ORF

### ISSUE THREAD

**Issue by lpg-tech** [hl7ch/ch-lab-order#121]
https://github.com/hl7ch/ch-orf/issues/53 (Feedback 1)
https://github.com/hl7ch/ch-orf/issues/80
https://github.com/hl7ch/ch-orf/issues/65
https://github.com/hl7ch/ch-orf/issues/64
https://github.com/hl7ch/ch-orf/issues/60
https://github.com/hl7ch/ch-orf/issues/91
https://github.com/hl7ch/ch-orf/issues/31#issuecomment-958979078
https://github.com/hl7ch/ch-orf/issues/50
https://github.com/hl7ch/ch-orf/issues/57

**Comment by PeroGrgic** [comment]
Die Anpassungen sind in den Beispielen. Sollen aber auch im Questionnaire angepasst werden.

**Comment by PeroGrgic** [comment]
Das im [Issue hl7ch/ch-orf#57](https://github.com/hl7ch/ch-orf/issues/57) erwähnte receiver.organization.**gln** fehlt noch.

**Comment by PeroGrgic** [comment]
receiverCopy.practitionerRole.practitioner.**gln** und receiverCopy.practitionerRole.practitioner.**zsr** sind nicht im ORF und RAD-Order. Nach Absprache in der Telco (26.01) sind beide Werte nicht notwendig beim recieverCopy und sollen entfernt werden.

**Comment by PeroGrgic** [comment]
Issue reviewed and closed.
