### ISSUE TITLE
Translations of Use Cases and Case Studies

### ISSUE THREAD

**Issue by lpg-tech** [hl7ch/ch-lab-order#148]
Needs Translations to German and French

**Comment by pjolo** [comment]
@lpg-tech:
I have linked the Example 1-tvt.json in the French translation of the Case Studies: https://build.fhir.org/ig/hl7ch/ch-lab-order/branches/develop/casestudies-french.html#etude-de-cas-1--suspicion-de-thrombose-veineuse-profonde 


Use Case 6 is only available in English. Shouldn't this use case also be translated into [German ](https://build.fhir.org/ig/hl7ch/ch-lab-order/branches/develop/casestudies-german.html) and [French](https://build.fhir.org/ig/hl7ch/ch-lab-order/branches/develop/casestudies-french.html )? There are also links in the English version to examples 6 that do not exist. Wouldn't it be better to remove these links?

**Comment by lpg-tech** [comment]
Case study 6: added translation to German and French

**Comment by pjolo** [comment]
I am closing this ticket as it has already been implemented
