### ISSUE TITLE
example-resource

### ISSUE THREAD

**Issue by lpg-tech** [hl7ch/ch-lab-order#19]

**Comment by isels1** [comment]
Needs further resource validation.
For example: Resource `bundle/referral-2-pertussis` fails at validating (ig publisher) with no exception.

---
To get the validation up and running for a resource, the resource needs to be included in the `ch.fhir.ig.ch-lab-order.xml` file inside the `definition` tag.

Example:
```xml
<resource>
      <reference>
        <reference value="Bundle/referral-1-tvt"/>
      </reference>
      <name value="referral-1-tvt"/>
      <description value="Example Bundle for referral/order for a TVT"/>
</resource>
```

**Comment by isels1** [comment]
Uploaded now some composition resources.
Result of validation can be found here:
http://build.fhir.org/ig/hl7ch/ch-lab-order/branches/19-example-resource/qa.html

**Comment by isels1** [comment]
example resources are done. closing this issue according merge #22
