### ISSUE TITLE
shift license to CC0 1.0 Universal (CC0 1.0)

### ISSUE THREAD

**Issue by lpg-tech** [hl7ch/ch-lab-order#253]
propose to switch to https://creativecommons.org/publicdomain/zero/1.0/ as the FHIR spec itself,
see https://github.com/hl7ch/ch-core/issues/226

**Comment by lpg-tech** [comment]
Switched to CC:
On Home page:
IP Statements
This document is licensed under Creative Commons “No Rights Reserved” ([CC0](https://creativecommons.org/publicdomain/zero/1.0/)).

**Comment by pjolo** [comment]
The changes are good.
