### ISSUE TITLE
Case Studies in German (Gabriel Hess, BFH I4MI)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-lab-order#272]
ch.fhir.ig.ch-lab-order#2.0.0-ballot /casestudies-german.html

Die beiden Links "6-histopath-mod.xml" und "6-histopath-mod.json" im Kapitel 3.6 Fallbeispiel 6 funktionieren nicht.

Gabriel Hess, BFH I4MI

**Comment by pjolo** [comment]
Good
