### ISSUE TITLE
Use Cases in German (Corina von Känel - CISTEC AG)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-lab-order#273]
ch.fhir.ig.ch-lab-order#2.0.0-ballot /usecases-german.html

UseCase1: "Dort weist ihnen das Laborinformationssystem einen eigenen Identifier (Specimen.accessionIdentifier) zu."
Should be phrased as an option. If possible the usage of an numbering system that can be used in the LIS should be prefered. Relabeling should be limmited to a minimum.

Corina von Känel - CISTEC AG

**Comment by pjolo** [comment]
The use case was adjusted as part of the objection
