### ISSUE TITLE
CH LAB-ORDER Document Profile: Spelling (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-lab-order#274]
ch.fhir.ig.ch-lab-order#2.0.0-ballot /StructureDefinition-ch-lab-order-document.html

unify the spelling of the profile name: 
CH LAB-ORDER Document Profile -> CH LAB-Order Document Profile

Michaela Ziegler, ahdis ag

**Comment by lpg-tech** [comment]
Spelling is unified
https://build.fhir.org/ig/hl7ch/ch-lab-order/branches/IG-ohne-Q/artifacts.html

**Comment by pjolo** [comment]
Good
