### ISSUE TITLE
Ordering of Containers, Blood Pressure instruments should not be covered by lab order (Corina von Känel, CISTEC AG)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-lab-order#276]
ch.fhir.ig.ch-lab-order#2.0.0-ballot /

Ordering of non laboratory sample measurments should not be part of the Lab-Order eg "Many laboratories also offer services for monitoring vital signs, such as Blood pressure, ECG, pulse, which can be ordered." 

Corina von Känel, CISTEC AG

**Comment by pjolo** [comment]
Good for me
