### ISSUE TITLE
Management Summary Change - rewording (Corina von Känel, CISTEC AG)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-lab-order#277]
ch.fhir.ig.ch-lab-order#2.0.0-ballot /

The lab-order should define the structure of the lab-order so it can be used by different laboratories and different providers of PIS, KIS.
1. the partly or fully filled electronic order should be safeble in the order filler system, so it can be changed until the samples are scanned by the receiver laboratory
2. practitionar, patient and treatment information should be transferable to the electronic order
3. in the electronic order all available analyses should be presentable. a search option should be available
4. Analyses, Sample type, required Sample additiv and preanalytic handling should be presented
4a. Information for the sample taking should be storable for the person preparing the taking of blood
4b. A numbering system should be supported, so that relabeling at the laboratory can be limmited (eg. practitionar number + number-range)
5. The electronic order should be able to handle the request of analyses for samples that were sent at an earlier point of time.
6. The electronic order should receive updates on the process of the laboratory analyses: as sample received in laboratory, first results available, report finished.
7. (delete)

Corina von Känel, CISTEC AG

**Comment by pjolo** [comment]
Meeting with Emmanuel, Corina and Simon 25.10.2023

Resolution of the negative comment:
The management summary will be adapted according to Corina's suggestion. After the changes have been made, they will be discussed with Corina.

**Comment by pjolo** [comment]
The changes are good.
