### ISSUE TITLE
Use Cases in German: Profile for use case 2? (Emmanuel Eschmann, CISTEC)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-lab-order#279]
ch.fhir.ig.ch-lab-order#2.0.0-ballot /usecases-german.html

is it not necessary to define other profiles in addition to those defined in this IG for a laboratory prescription without the use of Questionnaire and QuestionnaireResponse?
If yes: Include the definition of the required profiles in this TODO as well.

Emmanuel Eschmann, CISTEC

**Comment by lpg-tech** [comment]
Profiles for Laboratory Order without use of Questionnaire and QuestionnaireResponse and Examples are ready:
https://build.fhir.org/ig/hl7ch/ch-lab-order/branches/master/profiles.html
and in Case Study Document menu item.

**Comment by pjolo** [comment]
Good
