### ISSUE TITLE
FHIR IGs must not have a TODO to be eligible for FMM Level 3 (Emmanuel Eschmann, CISTEC)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-lab-order#280]
ch.fhir.ig.ch-lab-order#2.0.0-ballot /usecases-german.html

According to the HL7 FHIR Conformance Criteria, FHIR IGs must not have a TODO to be eligible for FHIR maturity mode level 3 (FMM level 3; see: https://confluence.hl7.org/display/FHIR/Conformance+QA+Criteria, 1st paragraph and https://confluence.hl7.org/display/FHIR/Conformance+QA+Criteria#ConformanceQACriteria-Behavior-ImplementationGuide).
I assume that it is intended that the present ballot will raise the CH LAB order IG from version 2.0.0 to version 3.0.0. I furthermore assume that this corresponds to raising the IG from FMM level 2 to FMM level 3).
Therefore, all the TODOs listed in this IG must have been implemented before the balloted IG is eligible for FMM level 3 (2 TODOs on this page).

Emmanuel Eschmann, CISTEC

**Comment by pjolo** [comment]
Meeting with Emmanuel, Corina and Simon 25.10.2023

Resolution of the negative comment:
The open TODOs in the IG are resolved. The implementation guides generally do not have a maturity level.

**Comment by lpg-tech** [comment]
TODOS  resolved
