### ISSUE TITLE
Use Cases in German:  use case 10 a specialised case of use case 2? (Emmanuel Eschmann, CISTEC)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-lab-order#281]
ch.fhir.ig.ch-lab-order#2.0.0-ballot /usecases-german.html

Isn't use case 10 a specialised case of use case 2?
If yes: bring both use cases closer together and specify what is common and what is different.
If not: specify what makes them different.

Emmanuel Eschmann, CISTEC

**Comment by pjolo** [comment]
Good
