### ISSUE TITLE
Examples needed that indicate request of analyses and linked information (Corina von Känel)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-lab-order#282]
ch.fhir.ig.ch-lab-order#2.0.0-ballot /artifacts.html

Examples needed that show full order and how the information as diagnoses, medication ist linked with the service requests

Examples should be named referring to usecases
current "ch lab order" indication single service requests and a possible implementation of profiles (crea clearance)
Accessing Profil which indicates a specific implementation Elektrolyte, Creaclearance  does not work 
http://fhir.ch/ig/ch-lab-order/lab-compendium/PlanDefinition/Creatinine-Clearance

Experience with HL7 V2 shows that many interpretations are possible to send orders. 

Therefore best practicie examples should be shown in the ch-lab-order to facilitate a common implementation of all software providers. 

Missing examples in ch-lab order: 

the following illustration is not a validated example, but shows a graphic that can be easilly understood by everyone who already implemented electronic lab orders.

: green: Example for a request of a coagulation analysis. The PIS needs information about preanalytic condition for label printing and for the taking and storing of the blood sample. 
: blue: The Laboratory needs specific information about the medication of the patient. Additionally information could be indicated as mandatory or favored.

All information that is necessary for a correct analytic with indicating the dedicated reference range of the analyses must be part of an order and therefore represantable in the the ch-lab-order.

Corina von Känel

**Comment by ziegm** [comment]
![image](https://github.com/hl7ch/ch-lab-order/assets/32767151/fc76badb-1c04-41fb-88f8-a05c66c3ec1e)
in addition to the feedback, provided by Corina

**Comment by pjolo** [comment]
Meeting with Emmanuel, Corina and Simon 25.10.2023

Resolution of the negative comment:
Examples will be created that represent best practice. The examples will be discussed with Corina.

**Comment by lpg-tech** [comment]
Example from above realized in 
https://build.fhir.org/ig/hl7ch/ch-lab-order/branches/master/Bundle-0-best-practice-document.html

**Comment by pjolo** [comment]
good

**Comment by lpg-tech** [comment]
linking additional informations to ServiceRequest (SR): Example 0-best-practice medication, example Vit.D.

**Comment by CorinavonKaenel** [comment]
Ein Vorschlag für eine Empfehlung wie Informationen wie Medikation oder Diagnosen, welche zwingend zu Analysen angegeben werden müssen, wurde ergänzt.
Vielen Dank
