### ISSUE TITLE
Home - IG Fragments (Safety Considerations) (Patrick Jolo eHealth Suisse)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-lab-order#284]
ch.fhir.ig.ch-lab-order#2.0.0-ballot /

In the recommended fragments, the section with the safety considerations as in CH Core is missing http://fhir.ch/ig/ch-core/index.html

Patrick Jolo eHealth Suisse

**Comment by lpg-tech** [comment]
Has been added in IG-ohne-Q branch:
https://build.fhir.org/ig/hl7ch/ch-lab-order/branches/IG-ohne-Q/index.html
Issue can be closed

**Comment by pjolo** [comment]
The changes are good.
