### ISSUE TITLE
Table of Contents - Questionnaire (Oliver Egger, ahdis)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-lab-order#63]
ch.fhir.ig.ch-lab-order#0.1.0 /toc.html

It would be helpful to have a link for navigation and a page to the different questionnaires for the lab-order. If you click now on the menu Questionnaire you have to select one and arrive not on a page with all defined questionnaire. 

Oliver Egger, ahdis

**Comment by lpg-tech** [comment]
All questionnaires are under 10 Artifacts Summary, and the different Questionnaires are linked under their names, e.g. 10.2 questionnaire 1-tvt

**Comment by PeroGrgic** [comment]
@oliveregger is this solution ok for you?

**Comment by oliveregger** [comment]
@PeroGrgic yes, thanks.

**Comment by PeroGrgic** [comment]
Issue resolved and closed.
