### ISSUE TITLE
Questionnaires: title, type, category (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-lab-order#64]
ch.fhir.ig.ch-lab-order#0.1.0 /Questionnaire-1-tvt.html

The fields order.title, order.type and order.category are readonly in the CH ORF Questionnaire. May harmonise it with the CH ORF, taking these issues ([CH RAD-Order](https://github.com/hl7ch/ch-rad-order/issues/5), [CH ORF](https://github.com/hl7ch/ch-orf/issues/31)) into account.

Michaela Ziegler, ahdis ag

**Comment by lpg-tech** [comment]
All fields order.title, order.type and order.category in Q and QR completed

**Comment by PeroGrgic** [comment]
Issue reviewed and closed.
