### ISSUE TITLE
Home -  (Oliver Egger, ahdis)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-lab-order#65]
ch.fhir.ig.ch-lab-order#0.1.0 /

rad-order and etoc have the following addition form conformance:

Applications claiming for conformance with the CH RAD-Order Implementation Guide shall:
-Render (and in case of the Questionnaire filler allow for data entry) all elements of a questionnaire in the user interface (e.g. on screen, in print).
- For Clinical Information: Grouping of items and the order of items within shall be adequately reproduced according to the Questionnaire.

http://fhir.ch/ig/ch-rad-order/index.html#foundation

Could these requirements also be added to ch-lab-order? then a test like https://ehealthsuisse.ihe-europe.net/gazelle/testing/testsDefinition/viewTestPage.seam?id=13623&testKeyword=CH-RAD-ORDER_RenderAndGrouping could be added.

Oliver Egger, ahdis

**Comment by lpg-tech** [comment]
Text added

**Comment by PeroGrgic** [comment]
Tests will be added by IHE-Services. Issue Closed.
