### ISSUE TITLE
Home: Download link for npm package (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-lab-order#67]
ch.fhir.ig.ch-lab-order#0.1.0 /

Best practice would be to add the download link for the npm package on the home page: 
**Download**: You can download this implementation guide in npm format from [here](package.tgz).

Michaela Ziegler, ahdis ag

**Comment by lpg-tech** [comment]
Angepasst

**Comment by PeroGrgic** [comment]
Issue reviewed and closed.
