### ISSUE TITLE
Different questionnaires (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-lab-order#69]
ch.fhir.ig.ch-lab-order#0.1.0 /Questionnaire-1-tvt.html

Instead of five different questionnaires, could you do one in which you have the general part (patient, recipient, etc.) and a specific part (lab-specific questions)? And in the specific part you would differentiate what exactly is being ordered (similar to the RAD order)?

Michaela Ziegler, ahdis ag

**Comment by lpg-tech** [comment]
In 1 first step I divided each Q in a general and in a specific part. 

Hint from Michaela
"Aus meiner Sicht könntest du wie einen Questionnaire machen und dann eine Choice machen, welchen spezifischen Lab Teil du haben haben willst:
- General
- Choice
   - TVT -> wenn ja, dann alle Fragen aus diesem Teil
   - Sepsis -> wenn ja, dann alle Fragen aus diesem Teil
   - etc.

Wäre halt noch etwas Aufwand zum Umstellen."

**Comment by PeroGrgic** [comment]
Issue reviewed and closed.
