### ISSUE TITLE
CH LAB-Order Composition: Link to LAB-Order Service Request (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-lab-order#70]
ch.fhir.ig.ch-lab-order#0.1.0 /StructureDefinition-ch-lab-order-composition.html

The reference Composition.entry:ServiceRequest should be the LAB-Order one, not the ORF one.

Michaela Ziegler, ahdis ag

**Comment by lpg-tech** [comment]
Angepasst

**Comment by PeroGrgic** [comment]
Issue reviewed and closed.
