### ISSUE TITLE
"Fehlende/benötigte" Versicherungs-Informationen (Beat Heggli, Netcetera AG)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-lab-order#71]
ch.fhir.ig.ch-lab-order#0.1.0 /

Generell benötigen wir zusätzliche Attribute für die Versicherung (GLN-Nummer der Versicherung, Name, Policennummer Versichertenkartennummer)

Beat Heggli, Netcetera AG

**Comment by lpg-tech** [comment]
Das ist erfüllt, sie issue #74

**Comment by PeroGrgic** [comment]
Issue reviewed and closed.
