### ISSUE TITLE
ReceiverCopies sollte auch einen Identifier beinhalten (Beat Heggli)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-lab-order#73]
ch.fhir.ig.ch-lab-order#0.1.0 /

Bei der ReceiverCopies gehen wir davon dass auch eine GLN-Nummer neben dem Namen des Kopieempfängers als Identifikation möglich sein soll.

Beat Heggli

**Comment by lpg-tech** [comment]
Das ist der Fall, siehe issue #75

**Comment by PeroGrgic** [comment]
Issue reviewed and closed.
