### ISSUE TITLE
AHV/SSN auch in den Beispielen als Identifier aufführen ( Beat Heggli)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-lab-order#74]
ch.fhir.ig.ch-lab-order#0.1.0 /

Die SSN sollte in den Beispielen auch als möglicher Patienten-Identifier aufgeführt werden. in der Kommunikation innerhalb des Spitals wird die häufig verwendet.

 Beat Heggli

**Comment by lpg-tech** [comment]
Die SSN (die es leider in der Schweiz nicht gibt) ist im CodeSystem identifierType der HL7 Terminologie vorgesehen. Die AHV Nummer sollte aber meines Wissens nicht als Patienten Identifier verwendet werden, sondern nur der im System hinterlegte Identifier (local PID).
Für Abrechnungszwecke gibt es über insurance im SR das ValueSet Coverage Identifier Type:
http://fhir.ch/ig/ch-orf/CodeSystem-ch-orf-cs-coverageidentifiertype.html
Dort fehlt allerdings die AHV Nummer, die m.E. dort hingehört.

**Comment by PeroGrgic** [comment]
Issue reviewed and closed.
