### ISSUE TITLE
ID bei receiver und receiverOrganization (Beat Heggli)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-lab-order#75]
ch.fhir.ig.ch-lab-order#0.1.0 /

Bei Reciever und ReceiverOrganization wäre ein Identifier sinnvoll. Unsere Anwendug geht davon aus, dass wir Aufträge für verschiedene Labors erhalten und anhand des Identifiers unterscheiden wollen

Beat Heggli

**Comment by lpg-tech** [comment]
Dieser Issue wird im CH-ORF gelöst: ch-orf-receiver ist vom Typ Reference(CH Core PractitionerRole), mit Referenzen zu Practitioner und/oder Organization. Beide können Identifier:GLN oder Identifier:ZSR haben, siehe z. Bsp.
http://fhir.ch/ig/ch-core/StructureDefinition-ch-core-practitioner.html

**Comment by PeroGrgic** [comment]
Issue reviewed and closed.
