### ISSUE TITLE
Pathologie-Verordnungen werden genannt, fehlen jedoch in Case Study, UseCase und Beispielinstanzen (Emmanuel Eschmann, CISTEC AG)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-lab-order#77]
ch.fhir.ig.ch-lab-order#0.1.0 /

Die allgemeine Beschreibung unter «http://fhir.ch/ig/ch-lab-order/index.html#hl7-swiss-fhir-implementation-guide-for-generic-laboratory-order-forms» führt den Satz “In general, the Laboratory Implementation Guide can also be used for pathology orders” auf. Wenn Pathologie-Verordnungen schon explizit genannt werden, so sollte auch eine Case Study, ein UseCase und eine Beispielinstanz zu Pathologie-Verordnungen erstellt werden (je auf den Seiten "Case Studies" und "Use Cases").

Emmanuel Eschmann, CISTEC AG

**Comment by lpg-tech** [comment]
TODO Beispielinstanz für Path-Order erstellen

**Comment by pjolo** [comment]
This ticket is closed because it is done
