### ISSUE TITLE
Beispielinstanzen: Durchzuführender Test fehlt in ServiceRequest.code (Emmanuel Eschmann, CISTEC AG)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-lab-order#78]
ch.fhir.ig.ch-lab-order#0.1.0 /artifacts.html

Als Laborinformationssystem will ich aus ServiceRequest.code automatisiert auslesen können, welche Tests die Laborgeräte durchführen müssen.

Bsp.: https://hl7.org/fhir/R4/servicerequest-example-ft4.json.html :
"code": {
"coding": [
      {
        "system": "http://loinc.org",
        "code": "3024-7",
        "display": "Thyroxine (T4) free [Mass/volume] in Serum or Plasma"
      }
    ],
    "text": "Free T4"
  }

In den Beispielen des vorliegenden IG fehlt jedoch die Angabe eines ServiceRequest.code. 
Z.Bsp.: http://fhir.ch/ig/ch-lab-order/ServiceRequest-1-tvt.json.html , in welchem zwar in ServiceRequest.reasonCode eine Thrombose als Begründung für die angeforderte Laboruntersuchung angegeben wird, aber keine spezifische Laboruntersuchung in ServiceRequest.coding angefordert wird.

Emmanuel Eschmann, CISTEC AG

**Comment by lpg-tech** [comment]
TODO Anpassungen LabOrderQrToBundle.map

**Comment by PeroGrgic** [comment]
Issue reviewed and closed.
