### ISSUE TITLE
Use Cases in English: Beispielinstanzen fehlen (Emmanuel Eschmann, CISTEC AG)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-lab-order#79]
ch.fhir.ig.ch-lab-order#0.1.0 /usecases-english.html

Lediglich zum Use Case 4 liegt eine Beispielinstanz vor (und ist an jener Stelle mit dem entsprechenden UseCase verlinkt).
Empfehlung: Jeden UseCase mit einer passenden Beispielinstanz versehen.

Emmanuel Eschmann, CISTEC AG

**Comment by lpg-tech** [comment]
Use Case 1: Beispielformulare http://fhir.ch/ig/ch-lab-order/Questionnaire-1-tvt.html und http://fhir.ch/ig/ch-lab-order/Questionnaire-2-pertussis.html zugeordnet.
Use Case 2: Beispieldokument kann einfach durch Weglassen der Ressourcen Questionnaire/QuestionnaireResponse erzeugt werden
Use Case 3: Im ValueSet Servicerequest.category wird RequestForAdditionalExam angewählt
Use Case 4: Im ValueSet Servicerequest.category wird RequestForPrecedentReport angewählt
Use Case 5 (vorher Use Case 4): hat schon eine Beispielinstanz
Use Case 6: Beispielinstanz wird durch Austausch von Sender und Receiver erhalten, mit den entsprechenden zusätzlichen oder alternativen Laboruntersuchungen.
Use Case 7: Fragestellung, klinische Befunde etc. ServiceRequest.reasonCode ServiceRequest.reasonCode.text müssen auf den Questionnaire gemappt werden.
Use Case 8: Die Angaben zu Präanalytik befnden sich im Service Request und müssen noch auf den Questionnaire / QuestionnareResponse gemappt werden
Use Case 9: Anfordern von Monitoring-Untersuchungen von Vitaldaten sollen hier aussen vor bleiben zugunsten einer besseren Übersichtlichkeit des IG. Der Use Case wird deshalb fallen gelassen. Bei Bedarf kann er aber im CodeSystem ChLabOrderServiceRequestCategories aktiviert werden. Konsequenter wäre aber eine eigener IG für die Monitoring Untersuchungen mit der Resource DeviceRequest
Use Case 10: Hier sind die dazu Voraussetzungen momentan nicht gegeben, es fehlt ein Catalog Server, der die verschiedenen CatalogEntries, die ein Beispiellabor zu Verfügung stellen kann,

**Comment by PeroGrgic** [comment]
Issue reviewed and closed.

**Comment by PeroGrgic** [comment]
Since it is a feature request, this issue remains open.

**Comment by lpg-tech** [comment]
Es gibt einen Questionnaire mit einem allgemeinen Teil (ORF) und einem spezifischen Teil (LabOrder): LabOrder-form. Der spezifische Teil enthält die Auswahl der verschiedenen CaseStudies. 
Siehe auch 
https://github.com/hl7ch/ch-lab-order/issues/132

**Comment by pjolo** [comment]
This ticket is closed because it is done
