### ISSUE TITLE
Use Cases in German (Simon Walther, Corina von Känel, CISTEC AG)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-lab-order#88]
ch.fhir.ig.ch-lab-order#0.1.0 /usecases-german.html

Use Cases 7 und 8 können zusammenfügt werden
Vorschlag Titel «Zwingende oder gewünschte Angaben zur vollständigen Auftragsstellung bzw. für die Ergebnisinterpretation». Es gibt Analysen / Specimen (Probenmaterial) bezogene zwingende Angaben zu Patient, Anamnese, Medikation, Diagnose, etc. welche zur vollständigen Beauftragung oder zur Befundung benötigt werden. Beispiel vollständige Beauftragung: In Abhängigkeit der Angabe Schwangerschaftswoche, wird nach zusätzlichen Keimen beim Vaginalabstrich gesucht. Befundinterpretation: Angabe der oralen Antikoagulation für Gerinnungsanalysen, da die Interpretation des Ergebnisses von der Medikation abhängt.

Simon Walther, Corina von Känel, CISTEC AG

**Comment by lpg-tech** [comment]
UC 7 und 8 zusammenführen: Zustimmung, TODO
Titel zu diskutieren, Pränanalytik und Angaben zur Probe scheint mir treffender. Zwingende Angaben  zu Patient, Anamnese, Medikation, Diagnose, etc. machen meist wenig Sinn.

**Comment by lpg-tech** [comment]
The pre-analytical conditions and any limitations are specified in the laboratory catalogue. These include, for example, the fasting of the patient, the type of sample container, the storage period and temperature of the sample, the reasons for rejection, etc. In addition, the costs of Vitamim D determination are only covered by health insurance in certain situations, e.g. rickets, osteoporosis, etc.

**Comment by pjolo** [comment]
This ticket is closed because it is done
