### ISSUE TITLE
CH LAB-Order Composition (Simon Walther, Corina von Känel, CISTEC AG)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-lab-order#89]
ch.fhir.ig.ch-lab-order#0.1.0 /StructureDefinition-ch-lab-order-composition.html

Verwendung von Snomed und LOINC für die Beschreibungen von Analysen, Specimen, Entnahmestellen usw. Auch für Gruppierungen sollten keine Freitexte verwendet werden.
Zum Teil wird schon Snomed und LOINC verwendet, aber nicht überall wo das möglich ist.

Simon Walther, Corina von Känel, CISTEC AG

**Comment by lpg-tech** [comment]
Gruppierung der Analysen dürfte wohl mit den Lab Specialties die beste Abdeckung haben: https://wiki.ihe.net/index.php/1.3.6.1.4.1.19376.1.3.3.2.1. 
TODO: In den Beispielen ergänzen

**Comment by PeroGrgic** [comment]
Issue reviewed and closed.
